name: three_dart
description: three.js implement by Dart. Dart 3D library. an easy to use, lightweight, cross-platform, general purpose 3D library. 
version: 0.0.14
homepage: https://github.com/wasabia/three_dart

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  universal_html: ^2.2.4
  ffi: ^2.1.0
  image: ^4.0.02
  flutter_gl: ^0.0.21
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.3

flutter:
